


name: Build ESAPI Script - v17.0

on:
  workflow_dispatch:
    inputs:
      dateInput:
        description: 'Expiration Date'
        required: true
        default: '1/1/2024'

jobs:
  build:
    runs-on: windows-2019
    env:
      GITHUB_WORKSPACE_PACKAGES_PATH: packages\ESAPI.17.0.0\lib\net48\
      PROJECT_NAME: MAAS-BreastPlan-helper
      MAJOR_VERSION: 2
      MINOR_VERSION: 5
      PATCH_VERSION: 6
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Update Target Framework Version to 4.8
      uses: Nambers/ReplaceStringInFile@v1.1
      with:
        path: .\${{env.PROJECT_NAME}}.csproj
        oldString: "TargetFrameworkVersion>v[\\d\\.]+<"
        newString: 'TargetFrameworkVersion>v4.8<'

    - name: Update AssemblyInfo.cs
      id: update_assembly_info
      run: |
        .\.github\workflows\Update-AssemblyInfo.ps1 `
          -AssemblyInfoFilePath .\Properties\AssemblyInfo.cs `
          -ExpirationDate "${{ github.event.inputs.dateInput }}" `
          -MajorVersion ${{ env.MAJOR_VERSION }} `
          -MinorVersion ${{ env.MINOR_VERSION }} `
          -PatchVersion ${{ env.PATCH_VERSION }} `
          -BuildNumber ${{ env.BUILD_NUMBER }}
          
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: latest
    
    - name: Download nuget packages
      run: nuget install .\packages.config -OutputDirectory packages
   
    - name: Add VIC GitHub NuGet repository
      run: nuget source add
        -Name github `
        -Source "https://nuget.pkg.github.com/Varian-Innovation-Center/index.json" `
        -UserName craman96 `
        -Password ${{ secrets.GITHUB_TOKEN }} `
        -StorePasswordInClearText

    - name: Download nuget package
      run: nuget install ESAPI -Version 17.0.0 -OutputDirectory packages

    - name: Update hint paths in the csproj file
      run: |
        .\.github\workflows\Update-EsapiHintPaths.ps1 `
        -CsprojFilePath .\ `
        -CsprojFileName MAAS-BreastPlan-helper.csproj
          
    - name: Build Solution
      run: msbuild.exe .\MAAS-BreastPlan-helper.csproj /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="x64" /p:configuration="Debug"
        
    - name: Zip
      run: |
        Compress-Archive `
          -Path ".\bin\Debug\*" `
          -DestinationPath "${{ github.workspace }}/${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV170.zip"
    
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: ${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV17.1
        tag_name: ${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV17.1
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        body: |
          This is an official release of the **`${{ env.PROJECT_NAME }}`** project.
          Supported Eclipse version: `v17.1`.
          The generated dll is valid until `${{ github.event.inputs.dateInput }}`.
        files: ${{ github.workspace }}/${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV171.zip
